name: 'ci'
on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install --no-frozen-lockfile

      
      - name: '安装 playwright 框架运行环境'
        uses: maxmilton/action-setup-playwright@v1
        with:
          # 可选安装的测试浏览器: chromium, firefox, webkit
          browsers: chromium
          headless: true

      - name: '运行 packages/front-circle-test 包的自动化测试'
        run: npx playwright test test
        working-directory: packages/temrule
